### ISSUE TITLE
Input data when using pluralize add not correct

### ISSUE THREAD

**Issue by TuanLuu54** [fullstackreact/react-daily-ui#10]
Currently when we drag on slider header to 1, `day` value still `days` not `day` as expect. Reason duration value on slider header return a string not a number so `pluralize` not working fine.
Please take a look image below:
![pluralize-error](https://user-images.githubusercontent.com/9304546/29493551-d407e030-85c2-11e7-9eec-ef2756e694c3.png)

https://github.com/fullstackreact/react-daily-ui/blob/e232aa125bafdd5fa6bbdd21d5f0cc11b502d1ac/002-checkout/src/components/CheckoutArea/OrderSummary.js#L6

On description of `pluralize` here: https://www.npmjs.com/package/pluralize
It should be a number.

Thanks,

**Comment by mrscobbler** [comment]
Merged your pull request! Thanks for the help! 😄
