### ISSUE TITLE
Improper props attribute "name" being used

### ISSUE THREAD

**Issue by dsteplight** [fullstackreact/react-daily-ui#6]
id={this.props.name} should be id={this.props.id} 

You are calling it like 
```javascript
                                          <Input
                                                  id="name"
                                                  type="text"
                                                  placeholder="Jack-Edward Oliver" />
```

But using it like 
```javascript
                                  <input
                                          id={this.props.name}
                                          autoComplete="false"
                                          required
                                          type={this.props.type}
                                          placeholder={this.props.placeholder}
>>                                />
```
I'm new to React but I don't see where the "props.name" property exists.

**Comment by TuanLuu54** [comment]
Hi @dsteplight,

You're right. Exactly it should be `id={this.props.id}`. I have create PR [here](https://github.com/fullstackreact/react-daily-ui/pull/9). Could you please help us review and merge it @mrscobbler? 

@dsteplight : please assignees to @mrscobbler on right side of this issue to remind her know about it.

Thanks,

**Comment by mrscobbler** [comment]
Thanks for point this out! Appreciate the help. I've merged your pull request @TuanLuu54
